# Workflow name displayed in GitHub Actions
name: CI/CD Pipeline

# Trigger this workflow on every push to the main branch
on:
  push:
    branches: [main]

jobs:
  build-and-push:
    # Use GitHub's hosted Ubuntu runner
    runs-on: ubuntu-latest

    steps:
      # Pull your repo code into the runner
      - name: Checkout code
        uses: actions/checkout@v6

      # Build the Docker image using your Dockerfile
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: devops-pipeline-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG